### ISSUE TITLE
Pattern Repeat

### ISSUE THREAD

**Issue by Julaja** [johndoe31415/knitpi#1]
When you change the settings from single pattern to pattern repeat while the KnitPi is knitting, it inserts one row before repeating the pattern.

**Comment by johndoe31415** [comment]
Unsure if this solves your problem, but please check out version 45953b2 and see if it fixes your issue. Thanks! <3

**Comment by Julaja** [comment]
Yeah it works. Thank you :+1:

**Comment by johndoe31415** [comment]
😘
